### ISSUE TITLE
Strange behaviour with INSERT/CREATE/DROP

### ISSUE THREAD

**Issue by wwaites** [okfn/webstore#57]
Doing sql operations with webstore-client such as

```
CREATE TABLE foo (...)
DROP TABLE IF EXISTS foo;
INSERT INTO foo (bar, baz) SELECT * FROM zzz
```

gets a response from the server that looks like

```
{'state': 'error', 'message': 'OK'}
```

which causes the client to raise a rather confusing error message:

```
Traceback (most recent call last):
  File "det/query.py", line 51, in <module>
    wsdb.query(q)
  File "/usr/home/ww/src/webstore-client/webstore/client/__init__.py", line 233, in query
    headers={'Content-Type': 'application/json'})
  File "/usr/home/ww/src/webstore-client/webstore/client/__init__.py", line 181, in _request
    raise WebstoreClientException(response, data)
webstore.client.WebstoreClientException: OK
```

**Comment by rufuspollock** [comment]
Are the operations actually failing or is a case where operations pass but we get an erroneous message?

**Comment by wwaites** [comment]
The operations do not actually fail. Just the response is bad.
